name: Merge to develop workflow

on:
  - push:
    branches:
      - develop
  - workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: least pull request
        run: count=`gh pr list --repo miyatama/learn-gh-cli --state open --json "id" | jq '. | length'`; echo "retain pull request: ${count}"
