name: Merge to develop workflow

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: least pull request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          count=`gh pr list --repo miyatama/learn-gh-cli --state open --json "id" | jq '. | length'` \
          echo "retain pull request: ${count}"
